/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Ctroller.DeTaiDao;
import Model.DeTai;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author longa
 */
public class DeTaiView extends javax.swing.JPanel {
private DefaultTableModel tblModel;
    /**
     * Creates new form DeTai
     */
    public DeTaiView() {
        initComponents();
        initTable();
        loadDaTaTable();
    }
     private void initTable()//tạo bảng ko có các trường tương ứng trong csdl
    {
       tblModel=new DefaultTableModel();
       tblModel.setColumnIdentifiers(new String[] {"Mã Đề Tài","Tên Đề Tài","GVHD","SV Thực Hiện","Khoa","Công Nghệ Sử Dụng","Tiến Độ"});
       tbl.setModel(tblModel);
    }
    private void loadDaTaTable()//hàm hiển thị danh sách dữ liệu tài khoản
    {
        try{
        DeTaiDao dao=new DeTaiDao();
        List<DeTai> list=dao.timkiemALL();
        tblModel.setRowCount(0);
        for(DeTai it:list)
        {
            tblModel.addRow(new Object[]{
                it.getMaDeTai(),it.getTenDeTai(),it.getGVHD(),it.getTenSVThucHien(),it.getKhoa(),it.getCongNgheSuDung(),it.getTienDo()
            });
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bntluu = new javax.swing.JButton();
        txtGVHD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSV = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        txtKhoa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bntdetele = new javax.swing.JButton();
        txtCongNghe = new javax.swing.JTextField();
        txtMaDeTai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtTenDeTai = new javax.swing.JTextField();
        txtTienDo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("GVHD");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("SV thực hiện");

        bntluu.setBackground(new java.awt.Color(204, 255, 255));
        bntluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save2.png"))); // NOI18N
        bntluu.setText("Lưu");
        bntluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntluuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Khóa");

        btnupdate.setBackground(new java.awt.Color(204, 255, 255));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        btnupdate.setText("Cập Nhật");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Công nghệ sử dụng");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mã đề tai");

        bntdetele.setBackground(new java.awt.Color(204, 255, 255));
        bntdetele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        bntdetele.setText("Xóa");
        bntdetele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdeteleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên đề tài");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        txtTenDeTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDeTaiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tiến Độ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSV, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addComponent(txtGVHD)
                            .addComponent(txtMaDeTai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDeTai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTienDo)
                            .addComponent(txtCongNghe)
                            .addComponent(txtKhoa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bntluu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnupdate)
                        .addGap(63, 63, 63)
                        .addComponent(bntdetele, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGVHD)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSV)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCongNghe)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntdetele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntluu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntluuActionPerformed
        try{
            DeTai dt=new DeTai();
            dt.setMaDeTai(txtMaDeTai.getText());
            dt.setTenDeTai(txtTenDeTai.getText());
            dt.setGVHD(txtGVHD.getText());
            dt.setTenSVThucHien(txtSV.getText());
            dt.setKhoa(Integer.valueOf(txtKhoa.getText()));
            dt.setCongNgheSuDung(txtCongNghe.getText());
            dt.setTienDo(txtTienDo.getText());
            DeTaiDao dao= new DeTaiDao();
            if(dao.insert(dt)){

                String message = "Thêm thành công vào csdl";

                JOptionPane.showMessageDialog(null, message);
                loadDaTaTable();
            }
            else{
                String message1 = "Thêm không thành công vào csdl";

                JOptionPane.showMessageDialog(null, message1);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bntluuActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try{
            DeTai dt=new DeTai();
            dt.setMaDeTai(txtMaDeTai.getText());
            dt.setTenDeTai(txtTenDeTai.getText());
            dt.setGVHD(txtGVHD.getText());
            dt.setTenSVThucHien(txtSV.getText());
            dt.setKhoa(Integer.valueOf(txtKhoa.getText()));
            dt.setCongNgheSuDung(txtCongNghe.getText());
            dt.setTienDo(txtTienDo.getText());
            DeTaiDao dao= new DeTaiDao();
            if(dao.update(dt)){

                String message = "Đã sửa trong csdl";

                JOptionPane.showMessageDialog(null, message);
                loadDaTaTable();
            }
            else{
                String message1 = "Lỗi sửa không thành công";

                JOptionPane.showMessageDialog(null, message1);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void bntdeteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdeteleActionPerformed
        try{
            DeTaiDao dao= new DeTaiDao();
            if(dao.delete(txtMaDeTai.getText()))
            {
                String message = "Đã xóa trong csdl";

                JOptionPane.showMessageDialog(null, message);
                loadDaTaTable();
                jButton1ActionPerformed(evt);
            }
            else{
                String message1 = "Lỗi xóa không thành công";

                JOptionPane.showMessageDialog(null, message1);
            }

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bntdeteleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{

            {
                String id=txtMaDeTai.getText();
                DeTaiDao dao= new DeTaiDao();
                DeTai nt=dao.timkiem(id);
                if(nt !=null)
                {
                    txtMaDeTai.setText(nt.getMaDeTai());
                    txtTenDeTai.setText(nt.getTenDeTai());
                    txtGVHD.setText(nt.getGVHD());
                    txtSV.setText(nt.getTenSVThucHien());
                    String khoa=String.valueOf(nt.getKhoa());
                    txtKhoa.setText(khoa);
                    String thu=String.valueOf(nt.getCongNgheSuDung());
                    txtCongNghe.setText(thu);
                    txtTienDo.setText(nt.getTienDo());
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        try{
            int row=tbl.getSelectedRow();
            if(row>=0)
            {
                String id=(String) tbl.getValueAt(row, 0);
                DeTaiDao dao= new DeTaiDao();
                DeTai nt=dao.timkiem(id);
                if(nt !=null)
                {
                    txtMaDeTai.setText(nt.getMaDeTai());
                    txtTenDeTai.setText(nt.getTenDeTai());
                    txtGVHD.setText(nt.getGVHD());
                    txtSV.setText(nt.getTenSVThucHien());
                    String sokm=String.valueOf(nt.getKhoa());
                    txtKhoa.setText(sokm);
                    String thu=String.valueOf(nt.getCongNgheSuDung());
                    txtCongNghe.setText(thu);
                    txtTienDo.setText(nt.getTienDo());
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblMouseClicked

    private void txtTenDeTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDeTaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDeTaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntdetele;
    private javax.swing.JButton bntluu;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCongNghe;
    private javax.swing.JTextField txtGVHD;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaDeTai;
    private javax.swing.JTextField txtSV;
    private javax.swing.JTextField txtTenDeTai;
    private javax.swing.JTextField txtTienDo;
    // End of variables declaration//GEN-END:variables
}
